# Generated by Django 2.2.5 on 2020-06-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('정문 || 철문', '정문 || 철문'), ('쪽문', '쪽문')], default='쪽문', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
