# Generated by Django 2.2.5 on 2020-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200606_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(default='02-1111-1111', max_length=15),
        ),
    ]
